[project]
name = "celery-workflows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.3.1",
    "fastapi>=0.128.0",
    "flower>=2.0.1",
    "redis>=7.1.0",
    "uvicorn[standard]>=0.40.0",
]
