{{- if .Values.seaweedfs.enabled }}
{{- if .Values.seaweedfs.filer.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-seaweedfs-filer-local
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: filer
  ports:
  - name: http
    port: {{ .Values.seaweedfs.filer.port }}
    targetPort: {{ .Values.seaweedfs.filer.port }}
    nodePort: {{ .Values.seaweedfs.filer.nodePort }}
---
{{- end }}
{{- if .Values.seaweedfs.s3.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-seaweedfs-s3-local
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
  ports:
  - name: http
    port: {{ .Values.seaweedfs.s3.port }}
    targetPort: {{ .Values.seaweedfs.s3.port }}
    nodePort: {{ .Values.seaweedfs.s3.nodePort }}
{{- end }}
{{- end }}
