{{- if .Values.velero.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-velero-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = {{ .Values.velero.s3.accessKey }}
    aws_secret_access_key = {{ .Values.velero.s3.secretKey }}
{{- end }}
