apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command: ["uvicorn"]
          args:
            - "src.api.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
