apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-redis
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}