apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-worker
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args:
            - "-A"
            - "src.celery"
            - "worker"
            - "--loglevel=info"
            - "--events"
          env:
            - name: CELERY_BROKER_URL
              value: "redis://{{ .Values.appName }}-redis:{{ .Values.redis.port }}/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://{{ .Values.appName }}-redis:{{ .Values.redis.port }}/1"
