apiVersion: v2
name: celery-workflows
description: Helm chart for Celery workers, Redis, and Flower
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: seaweedfs
    version: 4.0.407
    repository: https://seaweedfs.github.io/seaweedfs/helm