apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flower
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-flower
  ports:
    - port: {{ .Values.flower.port }}
      targetPort: {{ .Values.flower.port }}
      nodePort: {{ .Values.flower.nodePort }}